In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Admin\Desktop\PYTHON\venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\Desktop\PYTHON\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.3 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/9.8 MB 1.3 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/9.8 MB 1.3 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/9.8 MB 1.3 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.8 MB 453.1 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.8 MB 906.3 kB/s eta 0:00:10
   ------ --------------------------------- 1.6/9.8 MB 953.2 kB/s eta 0:00:09
   ------ --------------------------------- 1.6/9.8 MB 953.2 kB/s eta 0:00:09
   ------- -------------------------------- 1.8/9.8 MB 831.8 kB/s eta 0:00:10
   --------- ------------------------------ 2.4/9.8 MB 938.3 kB/s eta 0:00:08
   --------- ------------------------------ 2.4/9.8 MB 938.3 kB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.8 MB 931.8 kB/s eta 0:00:08
   ----------- ---------------------------- 2.9/9.8 MB 916.6 kB/s eta 0:00:08
   ----------- ---------------------------- 2.9/9.8 MB 916.6 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.8 MB 895.8 kB/s eta 0:00:08
   ------------- -------------------------- 3.4/9.8 MB 902.6 kB/s eta 0:00:08
   ------------- -------------------------- 3.4/9.8 MB 902.6 kB/s eta 0:00:08
   -------------- ------------------------- 3.7/9.8 MB 890.2 kB/s eta 0:00:07
   --------------- ------------------------ 3.9/9.8 MB 886.3 kB/s eta 0:00:07
   --------------- ------------------------ 3.9/9.8 MB 886.3 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.8 MB 870.7 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.8 MB 870.7 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.8 MB 870.7 kB/s eta 0:00:07
   ------------------ --------------------- 4.5/9.8 MB 826.0 kB/s eta 0:00:07
   ------------------ --------------------- 4.5/9.8 MB 826.0 kB/s eta 0:00:07
   ------------------- -------------------- 4.7/9.8 MB 783.5 kB/s eta 0:00:07
   ------------------- -------------------- 4.7/9.8 MB 783.5 kB/s eta 0:00:07
   ------------------- -------------------- 4.7/9.8 MB 783.5 kB/s eta 0:00:07
   -------------------- ------------------- 5.0/9.8 MB 753.0 kB/s eta 0:00:07
   -------------------- ------------------- 5.0/9.8 MB 753.0 kB/s eta 0:00:07
   --------------------- ------------------ 5.2/9.8 MB 739.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.2/9.8 MB 739.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.2/9.8 MB 739.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.2/9.8 MB 739.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.2/9.8 MB 739.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.2/9.8 MB 739.5 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.8 MB 657.9 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.8 MB 657.9 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.8 MB 657.9 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.8 MB 657.9 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.8 MB 657.9 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.8 MB 657.9 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.8 MB 657.9 kB/s eta 0:00:07
   ----------------------- ---------------- 5.8/9.8 MB 572.8 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.8 MB 572.8 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.8 MB 572.8 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.8 MB 572.8 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.8 MB 572.8 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.8 MB 572.8 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.8 MB 572.8 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.8 MB 572.8 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.8 MB 512.6 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.8 MB 512.6 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.8 MB 512.6 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.8 MB 512.6 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.8 MB 512.6 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.8 MB 512.6 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.8 MB 512.6 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.8 MB 470.0 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.8 MB 470.0 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.8 MB 470.0 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.8 MB 470.0 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.8 MB 470.0 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.8 MB 447.9 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.8 MB 447.9 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.8 MB 447.9 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.8 MB 447.9 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.8 MB 447.9 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.8 MB 447.9 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.8 MB 429.7 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.8 MB 429.7 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.8 MB 429.7 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.8 MB 429.7 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.8 MB 429.7 kB/s eta 0:00:08
   ---------------------------- ----------- 7.1/9.8 MB 415.4 kB/s eta 0:00:07
   ---------------------------- ----------- 7.1/9.8 MB 415.4 kB/s eta 0:00:07
   ---------------------------- ----------- 7.1/9.8 MB 415.4 kB/s eta 0:00:07
   ---------------------------- ----------- 7.1/9.8 MB 415.4 kB/s eta 0:00:07
   ---------------------------- ----------- 7.1/9.8 MB 415.4 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.8 MB 406.3 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.8 MB 406.3 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.8 MB 406.3 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.8 MB 406.3 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.8 MB 406.3 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.8 MB 406.3 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.8 MB 406.3 kB/s eta 0:00:07
   ------------------------------ --------- 7.6/9.8 MB 388.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.6/9.8 MB 388.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.6/9.8 MB 388.2 kB/s eta 0:00:06
   ------------------------------- -------- 7.9/9.8 MB 387.4 kB/s eta 0:00:06
   ------------------------------- -------- 7.9/9.8 MB 387.4 kB/s eta 0:00:06
   ------------------------------- -------- 7.9/9.8 MB 387.4 kB/s eta 0:00:06
   ------------------------------- -------- 7.9/9.8 MB 387.4 kB/s eta 0:00:06
   --------------------------------- ------ 8.1/9.8 MB 385.1 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.8 MB 385.1 kB/s eta 0:00:05
   ---------------------------------- ----- 8.4/9.8 MB 387.8 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.8 MB 387.8 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.8 MB 387.8 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.8 MB 387.8 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.8 MB 384.9 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.8 MB 384.9 kB/s eta 0:00:04
   ------------------------------------ --- 8.9/9.8 MB 390.4 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.8 MB 390.4 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.8 MB 392.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.8 MB 392.3 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 397.8 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 397.8 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 397.8 kB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 402.4 kB/s  0:00:24
Installing collected packages: pandas
Successfully installed pandas-3.0.5

In [2]:
import pandas as pd

In [3]:
# series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index. A pandas Series is like a fixed-size dict in that you can get and set values by index label.

# ceating the series from list
data = [1, 2, 3, 4, 5]
series_from_list = pd.Series(data)
print("Series from list:\n", series_from_list)

Series from list:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# ceating the series from dictionary
data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
series_from_dict = pd.Series(data)
print("Series from dictionary:\n", series_from_dict)

Series from dictionary:
 a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
# give index to the series
data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
series_with_index = pd.Series(data, index=index)
print("Series with custom index:\n", series_with_index)

Series with custom index:
 a    10
b    20
c    30
d    40
e    50
dtype: int64

In [6]:
import numpy as np

In [7]:
arr = np.array(series_with_index)
print("Numpy array from pandas series:\n", arr)

Numpy array from pandas series:
 [10 20 30 40 50]

In [8]:
# DataFrame is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.

#creting the DataFrame from dictionary of list

data = {'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'age': [25, 30, 35, 40, 45],
        'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
        }

df=pd.DataFrame(data)
print("DataFrame from dictionary of lists:\n", df)

DataFrame from dictionary of lists:
       name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [9]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'age': [25, 30, 35, 40, 45],
        'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
        }
index=['row1', 'row2', 'row3', 'row4', 'row5']

df=pd.DataFrame(data, index=index)
print("DataFrame from dictionary of lists:\n", df)

DataFrame from dictionary of lists:
          name  age         city
row1    Alice   25     New York
row2      Bob   30  Los Angeles
row3  Charlie   35      Chicago
row4    David   40      Houston
row5      Eva   45      Phoenix

In [10]:
#creating the DataFrame from list of dictionaries

data = [{'name': 'Alice', 'age': 25, 'city': 'New York'},
        {'name': 'Bob', 'age': 30, 'city': 'Los Angeles'},
        {'name': 'Charlie', 'age': 35, 'city': 'Chicago'},
        {'name': 'David', 'age': 40, 'city': 'Houston'},
        {'name': 'Eva', 'age': 45, 'city': 'Phoenix'}]

df = pd.DataFrame(data)
print("DataFrame from list of dictionaries:\n", df)

DataFrame from list of dictionaries:
       name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [23]:
df = pd.read_csv('Practice.csv')
df.head(5)

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Product,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
0,ORD10001,CUST1001,2024-01-01,56.0,Male,Lahore,IT,Mouse,Office,6,105836.96,7.97,Cash,Completed,4.1,7.0,1,635021.76,50611.23,584410.53
1,ORD10002,CUST1002,2024-01-01,46.0,Female,Multan,HR,Headphones,Office,7,196373.45,26.87,Cash,Completed,1.4,1.0,9,1374614.15,369358.82,1005255.33
2,ORD10003,CUST1003,2024-01-02,32.0,Male,Burewala,Sales,Webcam,Electronics,4,49330.30,3.10,Cash,Returned,3.1,14.0,12,197321.20,6116.96,191204.24
3,ORD10004,CUST1004,2024-01-03,60.0,Female,Gujranwala,Sales,Tablet,Electronics,1,205153.20,19.70,JazzCash,Completed,1.9,7.0,13,205153.20,40415.18,164738.02
4,ORD10005,CUST1005,2024-01-04,25.0,Male,Karachi,Finance,Phone,Office,1,162362.40,27.21,EasyPaisa,Pending,1.7,4.0,15,162362.40,44178.81,118183.59

In [13]:
df.tail(5)

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Product,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
995,ORD10996,CUST1296,2026-07-27,23.0,Female,Rawalpindi,Finance,Webcam,Electronics,6,74056.90,17.14,Cash,Completed,1.4,7.0,6,444341.40,76160.12,368181.28
996,ORD10997,CUST1297,2026-07-28,43.0,Female,Multan,Marketing,Phone,Office,1,88959.78,22.36,JazzCash,Completed,2.2,5.0,10,88959.78,19891.41,69068.37
997,ORD10998,CUST1298,2026-07-29,21.0,Male,Burewala,IT,Headphones,Accessories,6,141366.22,11.37,Bank Transfer,Returned,3.5,4.0,10,848197.32,96440.04,751757.28
998,ORD10999,CUST1299,2026-07-30,36.0,Female,Rawalpindi,Sales,Mouse,Electronics,5,63454.52,9.08,EasyPaisa,Returned,4.2,8.0,6,317272.60,28808.35,288464.25
999,ORD11000,CUST1300,2026-07-31,37.0,Female,Peshawar,Marketing,Phone,Office,4,228864.84,13.78,EasyPaisa,Pending,4.6,4.0,3,915459.36,126150.30,789309.06

In [14]:
df['Product']

0           Mouse
1      Headphones
2          Webcam
3          Tablet
4           Phone
          ...
995        Webcam
996         Phone
997    Headphones
998         Mouse
999         Phone
Name: Product, Length: 1000, dtype: str

In [15]:
df.loc[0]

Order_ID                 ORD10001
Customer_ID              CUST1001
Date                   2024-01-01
Customer_Age                 56.0
Gender                       Male
City                       Lahore
Department                     IT
Product                     Mouse
Category                   Office
Quantity                        6
Unit_Price              105836.96
Discount_Percent             7.97
Payment_Method               Cash
Order_Status            Completed
Rating                        4.1
Delivery_Days                 7.0
Employee_Experience             1
Gross_Amount            635021.76
Discount_Amount          50611.23
Net_Amount              584410.53
Name: 0, dtype: object

In [18]:
df.iloc[0,1]

'CUST1001'

In [24]:
df.drop('Product', axis=1, inplace=True)

In [25]:
df

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
0,ORD10001,CUST1001,2024-01-01,56.0,Male,Lahore,IT,Office,6,105836.96,7.97,Cash,Completed,4.1,7.0,1,635021.76,50611.23,584410.53
1,ORD10002,CUST1002,2024-01-01,46.0,Female,Multan,HR,Office,7,196373.45,26.87,Cash,Completed,1.4,1.0,9,1374614.15,369358.82,1005255.33
2,ORD10003,CUST1003,2024-01-02,32.0,Male,Burewala,Sales,Electronics,4,49330.30,3.10,Cash,Returned,3.1,14.0,12,197321.20,6116.96,191204.24
3,ORD10004,CUST1004,2024-01-03,60.0,Female,Gujranwala,Sales,Electronics,1,205153.20,19.70,JazzCash,Completed,1.9,7.0,13,205153.20,40415.18,164738.02
4,ORD10005,CUST1005,2024-01-04,25.0,Male,Karachi,Finance,Office,1,162362.40,27.21,EasyPaisa,Pending,1.7,4.0,15,162362.40,44178.81,118183.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD10996,CUST1296,2026-07-27,23.0,Female,Rawalpindi,Finance,Electronics,6,74056.90,17.14,Cash,Completed,1.4,7.0,6,444341.40,76160.12,368181.28
996,ORD10997,CUST1297,2026-07-28,43.0,Female,Multan,Marketing,Office,1,88959.78,22.36,JazzCash,Completed,2.2,5.0,10,88959.78,19891.41,69068.37
997,ORD10998,CUST1298,2026-07-29,21.0,Male,Burewala,IT,Accessories,6,141366.22,11.37,Bank Transfer,Returned,3.5,4.0,10,848197.32,96440.04,751757.28
998,ORD10999,CUST1299,2026-07-30,36.0,Female,Rawalpindi,Sales,Electronics,5,63454.52,9.08,EasyPaisa,Returned,4.2,8.0,6,317272.60,28808.35,288464.25
999,ORD11000,CUST1300,2026-07-31,37.0,Female,Peshawar,Marketing,Office,4,228864.84,13.78,EasyPaisa,Pending,4.6,4.0,3,915459.36,126150.30,789309.06

In [26]:
df.describe()

,Customer_Age,Quantity,Unit_Price,Discount_Percent,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
count,980.000000,1000.000000,1000.000000,980.000000,980.000000,980.000000,1000.00000,1.000000e+03,1000.000000,1.000000e+03
mean,41.555102,4.095000,123347.394620,14.922490,2.987347,7.503061,7.31700,5.066321e+05,75819.252260,4.308129e+05
std,13.782271,2.004993,72044.055757,8.664013,1.114627,4.059440,4.53134,4.125564e+05,83587.400609,3.552755e+05
min,18.000000,1.000000,556.650000,0.120000,1.000000,1.000000,0.00000,1.298380e+03,30.220000,1.054280e+03
25%,30.000000,2.000000,61500.287500,7.397500,2.100000,4.000000,3.00000,1.669690e+05,16374.157500,1.387463e+05
50%,42.000000,4.000000,119038.540000,14.900000,3.000000,7.000000,7.00000,3.965717e+05,42624.795000,3.344275e+05
75%,53.000000,6.000000,185588.120000,22.525000,3.900000,11.000000,11.00000,7.471058e+05,107354.550000,6.383836e+05
max,65.000000,7.000000,249698.840000,29.980000,5.000000,14.000000,15.00000,1.730510e+06,476415.450000,1.687862e+06