In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv("heart-disease.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
x = df.drop("target", axis=1)
y = df["target"]

In [10]:
y.shape

(303,)

In [5]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Admin\Desktop\PYTHON\venv\Lib\site-packages (from scikit-learn) (2.5.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Admin\Desktop\PYTHON\venv\Lib\site-packages (from scikit-learn) (2.24.0)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 541.6 kB/s eta 0:00:15
   -- ------------------------------------- 0.5/8.2 MB 541.6 kB/s eta 0:00:15
   --- ------------------------------------ 0.8/8.2 MB 610.3 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/8.2 MB 610.3 kB/s eta 0:00:13
   ----- ---------------------------------- 1.0/8.2 MB 671.0 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.2 MB 706.6 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/8.2 MB 749.0 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.2 MB 774.4 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.2 MB 774.4 kB/s eta 0:00:09
   ---------- ----------------------------- 2.1/8.2 MB 772.6 kB/s eta 0:00:08
   ---------- ----------------------------- 2.1/8.2 MB 772.6 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.2 MB 737.4 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.2 MB 737.4 kB/s eta 0:00:08
   ------------ --------------------------- 2.6/8.2 MB 702.4 kB/s eta 0:00:08
   ------------ --------------------------- 2.6/8.2 MB 702.4 kB/s eta 0:00:08
   ------------ --------------------------- 2.6/8.2 MB 702.4 kB/s eta 0:00:08
   ------------ --------------------------- 2.6/8.2 MB 702.4 kB/s eta 0:00:08
   ------------ --------------------------- 2.6/8.2 MB 702.4 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.2 MB 652.1 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.2 MB 652.1 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.2 MB 652.1 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.2 MB 652.1 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.2 MB 599.2 kB/s eta 0:00:09
   ---------------- ----------------------- 3.4/8.2 MB 599.2 kB/s eta 0:00:09
   ---------------- ----------------------- 3.4/8.2 MB 599.2 kB/s eta 0:00:09
   ----------------- ---------------------- 3.7/8.2 MB 578.5 kB/s eta 0:00:08
   ----------------- ---------------------- 3.7/8.2 MB 578.5 kB/s eta 0:00:08
   ----------------- ---------------------- 3.7/8.2 MB 578.5 kB/s eta 0:00:08
   ------------------- -------------------- 3.9/8.2 MB 570.1 kB/s eta 0:00:08
   ------------------- -------------------- 3.9/8.2 MB 570.1 kB/s eta 0:00:08
   -------------------- ------------------- 4.2/8.2 MB 570.6 kB/s eta 0:00:08
   -------------------- ------------------- 4.2/8.2 MB 570.6 kB/s eta 0:00:08
   --------------------- ------------------ 4.5/8.2 MB 572.4 kB/s eta 0:00:07
   --------------------- ------------------ 4.5/8.2 MB 572.4 kB/s eta 0:00:07
   ---------------------- ----------------- 4.7/8.2 MB 572.7 kB/s eta 0:00:07
   ---------------------- ----------------- 4.7/8.2 MB 572.7 kB/s eta 0:00:07
   ------------------------ --------------- 5.0/8.2 MB 575.2 kB/s eta 0:00:06
   ------------------------ --------------- 5.0/8.2 MB 575.2 kB/s eta 0:00:06
   ------------------------- -------------- 5.2/8.2 MB 574.3 kB/s eta 0:00:06
   ------------------------- -------------- 5.2/8.2 MB 574.3 kB/s eta 0:00:06
   -------------------------- ------------- 5.5/8.2 MB 571.6 kB/s eta 0:00:05
   -------------------------- ------------- 5.5/8.2 MB 571.6 kB/s eta 0:00:05
   -------------------------- ------------- 5.5/8.2 MB 571.6 kB/s eta 0:00:05
   -------------------------- ------------- 5.5/8.2 MB 571.6 kB/s eta 0:00:05
   -------------------------- ------------- 5.5/8.2 MB 571.6 kB/s eta 0:00:05
   ---------------------------- ----------- 5.8/8.2 MB 536.2 kB/s eta 0:00:05
   ---------------------------- ----------- 5.8/8.2 MB 536.2 kB/s eta 0:00:05
   ----------------------------- ---------- 6.0/8.2 MB 538.0 kB/s eta 0:00:05
   ----------------------------- ---------- 6.0/8.2 MB 538.0 kB/s eta 0:00:05
   ----------------------------- ---------- 6.0/8.2 MB 538.0 kB/s eta 0:00:05
   ------------------------------ --------- 6.3/8.2 MB 537.4 kB/s eta 0:00:04
   ------------------------------ --------- 6.3/8.2 MB 537.4 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 536.9 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 536.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 538.4 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.2 MB 538.4 kB/s eta 0:00:03
   ---------------------------------- ----- 7.1/8.2 MB 537.9 kB/s eta 0:00:03
   ---------------------------------- ----- 7.1/8.2 MB 537.9 kB/s eta 0:00:03
   ---------------------------------- ----- 7.1/8.2 MB 537.9 kB/s eta 0:00:03
   ----------------------------------- ---- 7.3/8.2 MB 537.3 kB/s eta 0:00:02
   ----------------------------------- ---- 7.3/8.2 MB 537.3 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.2 MB 536.9 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.2 MB 536.9 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 534.6 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 534.6 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 534.6 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 534.6 kB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 525.4 kB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 525.4 kB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 516.5 kB/s  0:00:15
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.18.1-cp312-cp312-win_amd64.whl (36.7 MB)
   ---------------------------------------- 0.0/36.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.7 MB ? eta -:--:--
    --------------------------------------- 0.5/36.7 MB 508.0 kB/s eta 0:01:12
    --------------------------------------- 0.5/36.7 MB 508.0 kB/s eta 0:01:12
    --------------------------------------- 0.5/36.7 MB 508.0 kB/s eta 0:01:12
    --------------------------------------- 0.8/36.7 MB 516.0 kB/s eta 0:01:10
    --------------------------------------- 0.8/36.7 MB 516.0 kB/s eta 0:01:10
   - -------------------------------------- 1.0/36.7 MB 508.4 kB/s eta 0:01:11
   - -------------------------------------- 1.0/36.7 MB 508.4 kB/s eta 0:01:11
   - -------------------------------------- 1.0/36.7 MB 508.4 kB/s eta 0:01:11
   - -------------------------------------- 1.3/36.7 MB 504.6 kB/s eta 0:01:11
   - -------------------------------------- 1.3/36.7 MB 504.6 kB/s eta 0:01:11
   - -------------------------------------- 1.3/36.7 MB 504.6 kB/s eta 0:01:11
   - -------------------------------------- 1.6/36.7 MB 463.5 kB/s eta 0:01:16
   - -------------------------------------- 1.6/36.7 MB 463.5 kB/s eta 0:01:16
   - -------------------------------------- 1.6/36.7 MB 463.5 kB/s eta 0:01:16
   - -------------------------------------- 1.6/36.7 MB 463.5 kB/s eta 0:01:16
   -- ------------------------------------- 1.8/36.7 MB 428.3 kB/s eta 0:01:22
   -- ------------------------------------- 1.8/36.7 MB 428.3 kB/s eta 0:01:22
   -- ------------------------------------- 1.8/36.7 MB 428.3 kB/s eta 0:01:22
   -- ------------------------------------- 2.1/36.7 MB 416.5 kB/s eta 0:01:23
   -- ------------------------------------- 2.1/36.7 MB 416.5 kB/s eta 0:01:23
   -- ------------------------------------- 2.1/36.7 MB 416.5 kB/s eta 0:01:23
   -- ------------------------------------- 2.1/36.7 MB 416.5 kB/s eta 0:01:23
   -- ------------------------------------- 2.4/36.7 MB 409.2 kB/s eta 0:01:24
   -- ------------------------------------- 2.4/36.7 MB 409.2 kB/s eta 0:01:24
   -- ------------------------------------- 2.4/36.7 MB 409.2 kB/s eta 0:01:24
   -- ------------------------------------- 2.6/36.7 MB 403.7 kB/s eta 0:01:25
   -- ------------------------------------- 2.6/36.7 MB 403.7 kB/s eta 0:01:25
   -- ------------------------------------- 2.6/36.7 MB 403.7 kB/s eta 0:01:25
   --- ------------------------------------ 2.9/36.7 MB 398.5 kB/s eta 0:01:25
   --- ------------------------------------ 2.9/36.7 MB 398.5 kB/s eta 0:01:25
   --- ------------------------------------ 2.9/36.7 MB 398.5 kB/s eta 0:01:25
   --- ------------------------------------ 2.9/36.7 MB 398.5 kB/s eta 0:01:25
   --- ------------------------------------ 3.1/36.7 MB 386.9 kB/s eta 0:01:27
   --- ------------------------------------ 3.1/36.7 MB 386.9 kB/s eta 0:01:27
   --- ------------------------------------ 3.1/36.7 MB 386.9 kB/s eta 0:01:27
   --- ------------------------------------ 3.1/36.7 MB 386.9 kB/s eta 0:01:27
   --- ------------------------------------ 3.4/36.7 MB 384.9 kB/s eta 0:01:27
   --- ------------------------------------ 3.4/36.7 MB 384.9 kB/s eta 0:01:27
   --- ------------------------------------ 3.4/36.7 MB 384.9 kB/s eta 0:01:27
   --- ------------------------------------ 3.4/36.7 MB 384.9 kB/s eta 0:01:27
   ---- ----------------------------------- 3.7/36.7 MB 370.9 kB/s eta 0:01:29
   ---- ----------------------------------- 3.7/36.7 MB 370.9 kB/s eta 0:01:29
   ---- ----------------------------------- 3.7/36.7 MB 370.9 kB/s eta 0:01:29
   ---- ----------------------------------- 3.7/36.7 MB 370.9 kB/s eta 0:01:29
   ---- ----------------------------------- 3.7/36.7 MB 370.9 kB/s eta 0:01:29
   ---- ----------------------------------- 3.9/36.7 MB 361.4 kB/s eta 0:01:31
   ---- ----------------------------------- 3.9/36.7 MB 361.4 kB/s eta 0:01:31
   ---- ----------------------------------- 3.9/36.7 MB 361.4 kB/s eta 0:01:31
   ---- ----------------------------------- 3.9/36.7 MB 361.4 kB/s eta 0:01:31
   ---- ----------------------------------- 4.2/36.7 MB 353.9 kB/s eta 0:01:32
   ---- ----------------------------------- 4.2/36.7 MB 353.9 kB/s eta 0:01:32
   ---- ----------------------------------- 4.2/36.7 MB 353.9 kB/s eta 0:01:32
   ---- ----------------------------------- 4.2/36.7 MB 353.9 kB/s eta 0:01:32
   ---- ----------------------------------- 4.5/36.7 MB 348.6 kB/s eta 0:01:33
   ---- ----------------------------------- 4.5/36.7 MB 348.6 kB/s eta 0:01:33
   ---- ----------------------------------- 4.5/36.7 MB 348.6 kB/s eta 0:01:33
   ---- ----------------------------------- 4.5/36.7 MB 348.6 kB/s eta 0:01:33
   ----- ---------------------------------- 4.7/36.7 MB 345.3 kB/s eta 0:01:33
   ----- ---------------------------------- 4.7/36.7 MB 345.3 kB/s eta 0:01:33
   ----- ---------------------------------- 4.7/36.7 MB 345.3 kB/s eta 0:01:33
   ----- ---------------------------------- 4.7/36.7 MB 345.3 kB/s eta 0:01:33
   ----- ---------------------------------- 5.0/36.7 MB 343.2 kB/s eta 0:01:33
   ----- ---------------------------------- 5.0/36.7 MB 343.2 kB/s eta 0:01:33
   ----- ---------------------------------- 5.0/36.7 MB 343.2 kB/s eta 0:01:33
   ----- ---------------------------------- 5.2/36.7 MB 343.9 kB/s eta 0:01:32
   ----- ---------------------------------- 5.2/36.7 MB 343.9 kB/s eta 0:01:32
   ----- ---------------------------------- 5.2/36.7 MB 343.9 kB/s eta 0:01:32
   ------ --------------------------------- 5.5/36.7 MB 347.3 kB/s eta 0:01:30
   ------ --------------------------------- 5.5/36.7 MB 347.3 kB/s eta 0:01:30
   ------ --------------------------------- 5.5/36.7 MB 347.3 kB/s eta 0:01:30
   ------ --------------------------------- 5.8/36.7 MB 352.0 kB/s eta 0:01:28
   ------ --------------------------------- 5.8/36.7 MB 352.0 kB/s eta 0:01:28
   ------ --------------------------------- 6.0/36.7 MB 358.0 kB/s eta 0:01:26
   ------ --------------------------------- 6.0/36.7 MB 358.0 kB/s eta 0:01:26
   ------ --------------------------------- 6.3/36.7 MB 365.4 kB/s eta 0:01:24
   ------- -------------------------------- 6.6/36.7 MB 373.5 kB/s eta 0:01:21
   ------- -------------------------------- 6.6/36.7 MB 373.5 kB/s eta 0:01:21
   ------- -------------------------------- 6.8/36.7 MB 382.3 kB/s eta 0:01:19
   ------- -------------------------------- 7.1/36.7 MB 390.5 kB/s eta 0:01:16
   ------- -------------------------------- 7.1/36.7 MB 390.5 kB/s eta 0:01:16
   ------- -------------------------------- 7.1/36.7 MB 390.5 kB/s eta 0:01:16
   -------- ------------------------------- 7.3/36.7 MB 389.2 kB/s eta 0:01:16
   -------- ------------------------------- 7.3/36.7 MB 389.2 kB/s eta 0:01:16
   -------- ------------------------------- 7.6/36.7 MB 397.8 kB/s eta 0:01:14
   -------- ------------------------------- 7.9/36.7 MB 404.8 kB/s eta 0:01:12
   -------- ------------------------------- 7.9/36.7 MB 404.8 kB/s eta 0:01:12
   -------- ------------------------------- 8.1/36.7 MB 411.5 kB/s eta 0:01:10
   --------- ------------------------------ 8.4/36.7 MB 417.7 kB/s eta 0:01:08
   --------- ------------------------------ 8.4/36.7 MB 417.7 kB/s eta 0:01:08
   --------- ------------------------------ 8.7/36.7 MB 422.1 kB/s eta 0:01:07
   --------- ------------------------------ 8.9/36.7 MB 429.2 kB/s eta 0:01:05
   --------- ------------------------------ 8.9/36.7 MB 429.2 kB/s eta 0:01:05
   ---------- ----------------------------- 9.2/36.7 MB 436.1 kB/s eta 0:01:04
   ---------- ----------------------------- 9.4/36.7 MB 442.5 kB/s eta 0:01:02
   ---------- ----------------------------- 9.7/36.7 MB 449.0 kB/s eta 0:01:01
   ---------- ----------------------------- 9.7/36.7 MB 449.0 kB/s eta 0:01:01
   ---------- ----------------------------- 10.0/36.7 MB 455.1 kB/s eta 0:00:59
   ----------- ---------------------------- 10.2/36.7 MB 461.3 kB/s eta 0:00:58
   ----------- ---------------------------- 10.5/36.7 MB 467.4 kB/s eta 0:00:57
   ----------- ---------------------------- 10.5/36.7 MB 467.4 kB/s eta 0:00:57
   ----------- ---------------------------- 10.7/36.7 MB 472.9 kB/s eta 0:00:55
   ------------ --------------------------- 11.0/36.7 MB 477.0 kB/s eta 0:00:54
   ------------ --------------------------- 11.0/36.7 MB 477.0 kB/s eta 0:00:54
   ------------ --------------------------- 11.0/36.7 MB 477.0 kB/s eta 0:00:54
   ------------ --------------------------- 11.0/36.7 MB 477.0 kB/s eta 0:00:54
   ------------ --------------------------- 11.5/36.7 MB 484.5 kB/s eta 0:00:52
   ------------ --------------------------- 11.5/36.7 MB 484.5 kB/s eta 0:00:52
   ------------ --------------------------- 11.8/36.7 MB 483.7 kB/s eta 0:00:52
   ------------ --------------------------- 11.8/36.7 MB 483.7 kB/s eta 0:00:52
   ------------ --------------------------- 11.8/36.7 MB 483.7 kB/s eta 0:00:52
   ------------- -------------------------- 12.1/36.7 MB 482.4 kB/s eta 0:00:51
   ------------- -------------------------- 12.1/36.7 MB 482.4 kB/s eta 0:00:51
   ------------- -------------------------- 12.3/36.7 MB 483.3 kB/s eta 0:00:51
   ------------- -------------------------- 12.3/36.7 MB 483.3 kB/s eta 0:00:51
   ------------- -------------------------- 12.3/36.7 MB 483.3 kB/s eta 0:00:51
   ------------- -------------------------- 12.6/36.7 MB 483.2 kB/s eta 0:00:50
   ------------- -------------------------- 12.6/36.7 MB 483.2 kB/s eta 0:00:50
   -------------- ------------------------- 12.8/36.7 MB 485.7 kB/s eta 0:00:50
   -------------- ------------------------- 12.8/36.7 MB 485.7 kB/s eta 0:00:50
   -------------- ------------------------- 13.1/36.7 MB 485.3 kB/s eta 0:00:49
   -------------- ------------------------- 13.1/36.7 MB 485.3 kB/s eta 0:00:49
   -------------- ------------------------- 13.4/36.7 MB 486.6 kB/s eta 0:00:48
   -------------- ------------------------- 13.4/36.7 MB 486.6 kB/s eta 0:00:48
   -------------- ------------------------- 13.6/36.7 MB 487.8 kB/s eta 0:00:48
   -------------- ------------------------- 13.6/36.7 MB 487.8 kB/s eta 0:00:48
   --------------- ------------------------ 13.9/36.7 MB 489.6 kB/s eta 0:00:47
   --------------- ------------------------ 13.9/36.7 MB 489.6 kB/s eta 0:00:47
   --------------- ------------------------ 14.2/36.7 MB 490.7 kB/s eta 0:00:46
   --------------- ------------------------ 14.2/36.7 MB 490.7 kB/s eta 0:00:46
   --------------- ------------------------ 14.2/36.7 MB 490.7 kB/s eta 0:00:46
   --------------- ------------------------ 14.4/36.7 MB 491.8 kB/s eta 0:00:46
   --------------- ------------------------ 14.4/36.7 MB 491.8 kB/s eta 0:00:46
   ---------------- ----------------------- 14.7/36.7 MB 493.2 kB/s eta 0:00:45
   ---------------- ----------------------- 14.7/36.7 MB 493.2 kB/s eta 0:00:45
   ---------------- ----------------------- 14.9/36.7 MB 494.2 kB/s eta 0:00:44
   ---------------- ----------------------- 14.9/36.7 MB 494.2 kB/s eta 0:00:44
   ---------------- ----------------------- 15.2/36.7 MB 495.3 kB/s eta 0:00:44
   ---------------- ----------------------- 15.2/36.7 MB 495.3 kB/s eta 0:00:44
   ---------------- ----------------------- 15.5/36.7 MB 495.5 kB/s eta 0:00:43
   ---------------- ----------------------- 15.5/36.7 MB 495.5 kB/s eta 0:00:43
   ----------------- ---------------------- 15.7/36.7 MB 497.1 kB/s eta 0:00:43
   ----------------- ---------------------- 15.7/36.7 MB 497.1 kB/s eta 0:00:43
   ----------------- ---------------------- 16.0/36.7 MB 498.3 kB/s eta 0:00:42
   ----------------- ---------------------- 16.0/36.7 MB 498.3 kB/s eta 0:00:42
   ----------------- ---------------------- 16.3/36.7 MB 500.7 kB/s eta 0:00:41
   ----------------- ---------------------- 16.3/36.7 MB 500.7 kB/s eta 0:00:41
   ------------------ --------------------- 16.5/36.7 MB 506.5 kB/s eta 0:00:40
   ------------------ --------------------- 16.5/36.7 MB 506.5 kB/s eta 0:00:40
   ------------------ --------------------- 16.5/36.7 MB 506.5 kB/s eta 0:00:40
   ------------------ --------------------- 16.8/36.7 MB 508.1 kB/s eta 0:00:40
   ------------------ --------------------- 17.0/36.7 MB 515.1 kB/s eta 0:00:39
   ------------------ --------------------- 17.0/36.7 MB 515.1 kB/s eta 0:00:39
   ------------------ --------------------- 17.0/36.7 MB 515.1 kB/s eta 0:00:39
   ------------------ --------------------- 17.0/36.7 MB 515.1 kB/s eta 0:00:39
   ------------------ --------------------- 17.3/36.7 MB 512.7 kB/s eta 0:00:38
   ------------------- -------------------- 17.6/36.7 MB 516.1 kB/s eta 0:00:37
   ------------------- -------------------- 17.6/36.7 MB 516.1 kB/s eta 0:00:37
   ------------------- -------------------- 17.6/36.7 MB 516.1 kB/s eta 0:00:37
   ------------------- -------------------- 17.8/36.7 MB 519.1 kB/s eta 0:00:37
   ------------------- -------------------- 17.8/36.7 MB 519.1 kB/s eta 0:00:37
   ------------------- -------------------- 18.1/36.7 MB 522.4 kB/s eta 0:00:36
   ------------------- -------------------- 18.1/36.7 MB 522.4 kB/s eta 0:00:36
   ------------------- -------------------- 18.1/36.7 MB 522.4 kB/s eta 0:00:36

In [6]:
# choose the right model for the data
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [17]:
#fit the model
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [18]:
y_train.shape

(242,)

In [19]:
clf.fit(x_train, y_train)

RandomForestClassifier()

In [20]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
270,46,1,0,120,249,0,0,144,0,0.8,2,0,3
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2

In [21]:
clf.score(x_train,y_train)

1.0

In [22]:
clf.score(x_test, y_test)

0.8524590163934426

In [24]:
y_pred = clf.predict(x_test)
y_pred

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [26]:
import pickle
with open("First_ML_Model.pkl", "wb") as file:
    pickle.dump(clf, file)

In [60]:
df1= pd.read_csv("car-sales.csv")
df1.drop("Price",axis=1 , inplace = True)

In [61]:
df1["price"]= [22,33,44,55,6,7,5,8,6,7]
x = df1.drop("price",axis=1)
y = df1['price']
df1

     Make Colour  Odometer (KM)  Doors  price
0  Toyota  White         150043      4     22
1   Honda    Red          87899      4     33
2  Toyota   Blue          32549      3     44
3     BMW  Black          11179      5     55
4  Nissan  White         213095      4      6
5  Toyota  Green          99213      4      7
6   Honda   Blue          45698      4      5
7   Honda   Blue          54738      4      8
8  Toyota  White          60000      4      6
9  Nissan  White          31600      4      7

In [62]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Categorical columns
categorical_columns = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
# Create ColumnTransformer
ct = ColumnTransformer([
        ("one_hot",one_hot, categorical_columns)
    ],
    remainder='passthrough'
)

# Transform the data
X_encoded = ct.fit_transform(x)

print(X_encoded)

[[0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  1.50043e+05]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  8.78990e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 1.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00
  3.25490e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00
  1.11790e+04]
 [0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  2.13095e+05]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00
  1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  9.92130e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  4.56980e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  5.47380e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  6.00000e+04]
 [0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  3.16000e+04]]

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X_encoded,y,test_size=0.3)
x_train

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 9.92130e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 1.50043e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 5.47380e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 1.00000e+00, 1.11790e+04],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 3.16000e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 6.00000e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 3.25490e+04]])

In [82]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)

RandomForestRegressor()

In [83]:
model.score(x_train,y_train)

0.8171535260115607

In [84]:
model.score(x_test,y_test)

-0.37377430647291887

In [85]:
import pickle
pickle.dump(model, open("2nd Model of Practice.plk","wb"))